"""
C5AI+ v5.0 – Demo: End-to-End Integration with PCC Feasibility Tool.

This script demonstrates the complete integration workflow:

  1. Build synthetic C5AI+ input for Nordic Aqua Partners AS (3 sites)
  2. Run the C5AI+ forecasting pipeline
  3. Export risk_forecast.json
  4. Run PCC Feasibility Tool with the forecast integrated
  5. Compare static vs. C5AI+-enriched results

Usage
-----
    python examples/run_c5ai_demo.py

Output
------
  – demo_risk_forecast.json  (generated by C5AI+)
  – Console comparison of key metrics
"""

import json
import sys
from pathlib import Path

# ── Ensure project root is on path ────────────────────────────────────────────
ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))


def _banner(title: str):
    print()
    print("=" * 62)
    print(f"  {title}")
    print("=" * 62)


def _nok(v: float) -> str:
    if abs(v) >= 1_000_000_000:
        return f"NOK {v/1_000_000_000:,.1f} Mrd"
    return f"NOK {v/1_000_000:,.1f} M"


# ── Step 1: Build synthetic C5AI+ operator input ──────────────────────────────

def build_c5ai_input():
    """Construct synthetic C5AI+ input for Nordic Aqua Partners AS."""
    from c5ai_plus.data_models.biological_input import (
        C5AIOperatorInput,
        SiteMetadata,
        EnvironmentalObservation,
        LiceObservation,
        HABAlert,
    )

    sites = [
        SiteMetadata(
            site_id="hardanger-nord",
            site_name="Hardanger Nord",
            latitude=60.45,
            longitude=6.10,
            species="Atlantic Salmon",
            biomass_tonnes=2100,
            biomass_value_nok=151_200_000,
            years_in_operation=9,
            fjord_exposure="semi_exposed",
        ),
        SiteMetadata(
            site_id="hardanger-sor",
            site_name="Hardanger Sor",
            latitude=60.20,
            longitude=6.35,
            species="Atlantic Salmon",
            biomass_tonnes=1800,
            biomass_value_nok=129_600_000,
            years_in_operation=7,
            fjord_exposure="sheltered",
        ),
        SiteMetadata(
            site_id="sunnfjord-pros",
            site_name="Sunnfjord Prosessering",
            latitude=61.45,
            longitude=5.75,
            species="Atlantic Salmon",
            biomass_tonnes=600,
            biomass_value_nok=43_200_000,
            years_in_operation=4,
            fjord_exposure="sheltered",
        ),
    ]

    # Generate 3 years of synthetic monthly temperature data for 2 sites
    import numpy as np
    rng = np.random.default_rng(42)
    env_obs = []
    for site_id in ["hardanger-nord", "hardanger-sor"]:
        for year in range(2023, 2026):
            for month in range(1, 13):
                # Norwegian fjord seasonal temperature profile
                base_temp = 6.0 + 10.0 * np.sin(np.pi * (month - 3) / 12)
                temp = float(base_temp + rng.normal(0, 1.2))
                env_obs.append(EnvironmentalObservation(
                    site_id=site_id,
                    year=year,
                    month=month,
                    sea_temp_celsius=temp,
                    salinity_ppt=float(32.5 + rng.uniform(-1, 1)),
                    chlorophyll_ug_l=None,  # Not available
                ))

    # Sunnfjord only has 18 months (less than min_obs_for_ml_model=24)
    for year in range(2024, 2026):
        for month in range(1, 13 if year < 2025 else 7):
            env_obs.append(EnvironmentalObservation(
                site_id="sunnfjord-pros",
                year=year,
                month=month,
                sea_temp_celsius=float(5.5 + 9.0 * np.sin(np.pi * (month - 3) / 12) + rng.normal(0, 1)),
                salinity_ppt=None,
            ))

    # A few lice observations for the larger sites
    lice_obs = []
    for site_id in ["hardanger-nord", "hardanger-sor"]:
        for year in range(2023, 2026):
            for week in [5, 10, 15, 20, 25, 30, 35, 40, 45, 50]:
                # Seasonal lice burden: peaks in summer
                month = min(12, max(1, week // 4))
                burden = 0.2 + 0.4 * max(0, np.sin(np.pi * (month - 2) / 10))
                lice_obs.append(LiceObservation(
                    site_id=site_id,
                    year=year,
                    week=week,
                    avg_lice_per_fish=float(burden + rng.normal(0, 0.1)),
                    treatment_applied=burden > 0.45,
                    treatment_type="bath" if burden > 0.45 else None,
                ))

    # One historical HAB event for Hardanger Nord
    hab_alerts = [
        HABAlert(
            site_id="hardanger-nord",
            year=2023,
            month=7,
            alert_level="medium",
            species="Chrysochromulina sp.",
            duration_days=8,
            loss_nok=2_800_000,
        )
    ]

    return C5AIOperatorInput(
        operator_id="nordic-aqua-001",
        operator_name="Nordic Aqua Partners AS",
        sites=sites,
        env_observations=env_obs,
        lice_observations=lice_obs,
        hab_alerts=hab_alerts,
        forecast_years=5,
    )


# ── Step 2: Run C5AI+ pipeline ────────────────────────────────────────────────

def run_c5ai_pipeline(operator_input, static_loss: float, output_path: str):
    from c5ai_plus.pipeline import ForecastPipeline
    pipeline = ForecastPipeline(verbose=True)
    forecast = pipeline.run(
        operator_input,
        static_mean_annual_loss=static_loss,
        output_path=output_path,
    )
    return forecast


# ── Step 3: Run PCC tool with and without C5AI+ ───────────────────────────────

def run_pcc_tool(input_json_path: str, c5ai_path: str = None):
    with open(input_json_path, "r") as fh:
        raw = json.load(fh)

    if c5ai_path:
        raw["c5ai_forecast_path"] = c5ai_path

    from data.input_schema import validate_input
    from models.monte_carlo import MonteCarloEngine

    operator = validate_input(raw)
    engine = MonteCarloEngine(operator, n_simulations=5000, seed=42)
    sim = engine.run()
    return sim


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    _banner("C5AI+ v5.0 – Demo: Biological Risk Forecasting Integration")

    # Load static PCC input to get the static E[annual loss]
    static_input_path = ROOT / "data" / "sample_input.json"
    print(f"\nLaster PCC-input: {static_input_path}")

    static_sim = run_pcc_tool(str(static_input_path))
    print(f"  Statisk E[arlig tap]:  {_nok(static_sim.mean_annual_loss)}")
    print(f"  Statisk VaR 99.5%:    {_nok(static_sim.var_995)}")
    print(f"  C5AI+ beriket:        {static_sim.c5ai_enriched}")

    # Build C5AI+ input and run pipeline
    _banner("Steg 1: Bygg syntetisk C5AI+ input for Nordic Aqua Partners AS")
    c5ai_input = build_c5ai_input()
    print(f"  Operator: {c5ai_input.operator_name}")
    print(f"  Lokaliteter: {len(c5ai_input.sites)}")
    print(f"  Miljoobservasjoner: {len(c5ai_input.env_observations)}")
    print(f"  Lusregistreringer: {len(c5ai_input.lice_observations)}")
    print(f"  HAB-varsler: {len(c5ai_input.hab_alerts)}")

    _banner("Steg 2: Kjoer C5AI+ prognosepipeline")
    forecast_path = str(ROOT / "examples" / "demo_risk_forecast.json")
    forecast = run_c5ai_pipeline(c5ai_input, static_sim.mean_annual_loss, forecast_path)

    agg = forecast.operator_aggregate
    print(f"\n  C5AI+ prognose:")
    print(f"    Total E[arlig tap]:   {_nok(agg.total_expected_annual_loss)}")
    print(f"    Skalafaktor vs. stat: {agg.c5ai_vs_static_ratio:.3f}")
    print(f"    Tapsfordeling:")
    for rt, frac in agg.loss_breakdown_fractions.items():
        loss = agg.annual_expected_loss_by_type.get(rt, 0)
        print(f"      {rt:12s}: {_nok(loss):>14s}  ({frac:.1%})")

    _banner("Steg 3: Kjoer PCC-verktoy med C5AI+ integrert")
    c5ai_sim = run_pcc_tool(str(static_input_path), c5ai_path=forecast_path)

    print(f"\n  Sammenlikning:")
    print(f"  {'Metrikk':<30} {'Statisk':>14} {'C5AI+ beriket':>16}")
    print(f"  {'-'*62}")
    metrics = [
        ("E[arlig tap]", static_sim.mean_annual_loss, c5ai_sim.mean_annual_loss),
        ("Std. avvik arlig tap", static_sim.std_annual_loss, c5ai_sim.std_annual_loss),
        ("VaR 95%", static_sim.var_95, c5ai_sim.var_95),
        ("VaR 99.5%", static_sim.var_995, c5ai_sim.var_995),
        ("TVaR 95%", static_sim.tvar_95, c5ai_sim.tvar_95),
    ]
    for label, sv, cv in metrics:
        print(f"  {label:<30} {_nok(sv):>14} {_nok(cv):>16}")

    print(f"\n  C5AI+ skalafaktor brukt: {c5ai_sim.c5ai_scale_factor:.3f}")
    print(f"  C5AI+ beriket:          {c5ai_sim.c5ai_enriched}")
    if c5ai_sim.bio_loss_breakdown:
        print(f"  Biologisk risikofordeling (forste aar, snitt):")
        for rt, arr in c5ai_sim.bio_loss_breakdown.items():
            print(f"    {rt:12s}: {_nok(arr[:, 0].mean()):>12}")

    _banner("Demo fullfort")
    print(f"  Forecast-fil: {forecast_path}")
    print(f"  Legg til i sample_input.json:")
    print(f'    "c5ai_forecast_path": "{forecast_path}"')
    print()


if __name__ == "__main__":
    main()
